[project]
name = "py-flashcard-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "markdown>=3.10",
    "mypy>=1.18.2",
    "pygments>=2.19.2",
    "python-dotenv>=1.2.1",
]
